new pipline feature shipped at 2025-11-05

diff --git a/docker.yaml b/docker.yaml
--- a/docker.yaml
+++ b/docker.yaml
@@ -1,182 +1,217 @@
-name: test_build_deploy
+name: test_build_scan_push
 on:
   push:
     branches:
       - main
   pull_request: 
-    branches:
+    branches: 
       - main
   workflow_dispatch:
-permissions: 
-  contents: write
+permissions:
   id-token: write
-  security-events: write
+  contents: write
 concurrency:
-  group: ${{github.ref}}-ci
+  group: ${{github.ref}}-ci 
   cancel-in-progress: true
 env:
-  REGION: ${{vars.AWS_REGION}}
-  ROLE: ${{secrets.ROLE}}
-  REPO: ${{vars.ECR_REPO}}
-  REG: ${{vars.ECR_REG}}
-  PYTHON: '3.11'
+  region: ${{vars.AWS_REGION}}
+  ECR_REPO: ${{vars.ECR_REPO}}
+  ECR_REG: ${{vars.ECR_REG}}
+  AWS_ROLE: ${{secrets.ROLE}}
   IMAGE_TAG: ${{github.sha}}
-  Email: ${{secrets.Email}}
+  EMAIL: ${{secrets.EMAIL}}
 jobs:
   test:
     runs-on: ubuntu-latest
     steps:
-      - name: checkout code
+      - name: chechkout code 
         uses: actions/checkout@v4
-        with:
-          fetch-depth: 1
-      - name: setup python 
+        with: 
+          fetch-depth: 0
+      - name: setup python environment 
         uses: actions/setup-python@v5
         with:
-          python-version: ${{env.PYTHON}}
+          python-version: '3.11'
           cache: 'pip'
-      - name: install dependency 
+      - name: install dependency
         run: |
-          pip install --upgrade pip
+          pip install --upgrade pip 
           pip install -r src/requirements.txt
-      - name: run test 
-        run: pytest src/* -v --maxfail=1 --disable-warnings --cov=. --cov-report=term-missing
-      - name: run linting of code 
-        run: flake8 . --count --max-line-length=120 --statistics
-      - name: check code vulnerabilities
-        run: bandit -r . -l -s B101,B103,B104,B105
-      - name: check for dependency vulnerabilities
-        run: check safety --full-report || true 
-    #===============
-    #build
-    #===============
-  build:
+      - name: test application 
+        run: pytest src/* -v --disable-warnings --maxfail=1 --cov=. --cov-report=term-missing
+      - name: lint code 
+        run: flake8 . --max-line-length=120 --statistics
+      - name: scan code 
+        run: bandit -r . -ll -s B101,B102,B103,B104,B105
+      - name: scan dependency 
+        run: safety check --full-report || true 
+  #=============
+  #build 
+  #===========
+  build: 
+    runs-on: ubuntu-latest
+    timeout-minutes: 10 
+    needs: test
+    outputs:
+          image-tag: ${{ steps.save.outputs.image_ref }}
+    steps:
+      - name: chechkout repo 
+        uses: actions/checkout@v4 
+        with: 
+          fetch-depth: 0 
+      - name: setup docker 
+        uses: docker/setup-buildx-action@v3
+      - name: setup cache 
+        uses: actions/cache@v4 
+        with: 
+          path: ./buildx
+          key: ${{runner.os}}-buildx-${{github.sha}}
+          restore-keys: ${{runner.os}}-buildx 
+      - name: generate meta data 
+        uses: docker/metadata-action@v5
+        id: meta
+        with: 
+          images: ${{env.ECR_REG}}${{env.ECR_REPO}} 
+          tags: | 
+            type=sha,prefix=sha-
+            type=raw,value=latest 
+      - name: build image 
+        uses: docker/build-push-action@v2
+        with: 
+          context: .
+          push: false
+          load: true 
+          tags: ${{steps.meta.outputs.tags}}
+          labels: ${{steps.meta.outputs.labels}}
+          cache-from: type=gha 
+          cache-to: type=gha,mode=max
+      - name: check image
+        run: docker images
+      - name: save image
+        id: save
+        run: |
+          IMAGE_TAG=$(echo "${{ steps.meta.outputs.tags }}" | grep 'sha-' | head -n 2)
+          echo "Saving image: $IMAGE_TAG"
+          docker save "$IMAGE_TAG" -o images.tar
+          echo "image_ref=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
+
+              
+      - name: upload artifact 
+        uses: actions/upload-artifact@v4
+        with: 
+          name: images 
+          path: images.tar 
+          retention-days: 7 
+   #==============
+    #test_images
+    #============
+  test_image:
+    needs: build
     runs-on: ubuntu-latest
     timeout-minutes: 5
     outputs:
-      image-tag: ${{steps.meta.outputs.tags}}
-    needs: test
+      image_tag: ${{needs.build.outputs.image-tag}}
     steps:
-      - name: checkout code 
+      - name: download artifact 
+        uses: actions/download-artifact@v4 
+        with:
+          name: images 
+          path: . 
+      - name: load image to runner 
+        run: docker load -i images.tar
+      - name: checkout 
         uses: actions/checkout@v4
         with: 
-          fetch-depth: 1
-      - name: seutup docker build environement
-        uses: docker/setup-buildx-action@v3
-      - name: use cache for faster build
-        uses: actions/cache@v4
-        with:
-          path: ./buildx
-          key: ${{runner.os}}-buildx-${{github.sha}}
-          restore-keys: |
-            ${{runner.os}}-buildx-
-      - name: generate metadata tag and label
-        id: meta 
-        uses: docker/metadata-action@v5
-        with:
-          images: ${{env.REG}}${{env.REPO}}
-          tags: |
-            type=sha
-            type=raw,value=latest
-      - name: build images 
-        uses: docker/build-push-action@v4
-        with:
-          context: .
-          push: false
-          load: true
-          platforms: linux/amd64
-          tags: ${{steps.meta.outputs.tags}}
-          labels: ${{steps.meta.outputs.labels}}
-          cache-from: type=gha
-          cache-to: type=gha,mode=max
-
-      - name: check if images has been build 
-        run: docker images
-      - name: save images
-        run: docker save ${{env.REG}}${{env.REPO}}: -o images.tar
-      - name: upload artifact to github blob storage
-        uses: actions/upload-artifact@v4
-        with:
-          name: images
-          path: images.tar
-          retention-days: 7
-
- #==============
- #scan_images
- #=============
-  scan_images: 
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - name: get images 
-        uses: actions/download-artifact@v4
-        with:
-          name: images
-          path: .
-      - name: setup docker buildx 
-        uses: docker/setup-buildx-action@v3
-      - name: load image to local daemon
-        run: docker load -i images.tar
-      - name: scan images for vulnerabilities
-        uses: aquasecurity/trivy-action@0.33.0
-        with:
-          image-ref: ${{env.REG}}${{env.REPO}}:latest
-          format: table
-          ignore-unfixed: true #ignore issues that cant be patch with os, library
-          exit-code: 0 # if caught an error only raise a warning and not fail pipeline
-          severity: HIGH
-          vuln-type: 'os,library'
-
-  #================
-  #test image
-  #============
-  testing:
-    need: scan
-    runs-on: ubuntu-latest
-    steps:
-      - name: download artifact 
-        uses: actions/download-artifact@v4
-        with:
-          name: images
-          path: .
-      - name: load image into daemon 
-        run: docker load -i images.tar
+          fetch-depth: 0
       - name: run test on image 
-       
-#=============
-#push
-#==================
-  push:
-    needs: build
+        run: | 
+          docker run -d --name test-app -p 8080:8080 ${{needs.build.outputs.image-tag}}
+          retries=5
+          count_retry=0
+          interval=5
+          health_link="http://localhost:8080/health"
+          
+          until [ $count_retry -ge $retries ]; do 
+            status_code=$(curl -s -o /dev/null -w "%{http_code}" "$health_link" || true)
+            if [ $status_code == "200" ]; then
+            echo "On the $count_retry attempt the container ran successfully"
+            docker logs test-app
+            docker rm -f test-app
+            exit 0
+            fi 
+            count_retry=$((count_retry + 1))
+            echo "The number of attempt is $count_retry/$retries: testing failed with code $status_code"
+            sleep "$interval"
+          done 
+          echo "testing failed"
+          docker logs test-app
+          docker rm -f test-app
+          exit 1
+  
+  #================
+  #scan images
+  #============
+  scan: 
     runs-on: ubuntu-latest
     timeout-minutes: 5
-    if: github.ref == 'refs/heads/main' 
+    needs: test_image
+    outputs:
+      image-tag: ${{needs.test_image.outputs.image_tag}}
     steps:
       - name: download artifact 
         uses: actions/download-artifact@v4
         with:
           name: images
           path: .
-      - name: check if images has been downloaded
-        run: docker images
-      - name: load artifact to local daemon 
+      - name: check is image is available in daemon 
+        run: docker image
+      - name: load artifact 
         run: docker load -i images.tar
-      - name: login to amazon 
-        uses: aws-actions/configure-aws-credentials@v4
+      - name: scan images with trivy
+        uses: aquasecurity/trivy-action@0.33.0
         with: 
-          role-to-assume: ${{env.ROLE}}
-          aws-region: ${{env.REGION}}
+          image-ref: ${{needs.test_image.outputs.image_tag}}
+          format: table
+          ignore-unfixed: true
+          severity: HIGH,CRITICAL
+          exit-code: 0
+          vuln-type: 'os,library'
+   
+  #==============
+  #push to ecr
+  #==============
+  push:
+    runs-on: ubuntu-latest
+    if: github.ref == 'refs/heads/main'
+    timeout-minutes: 5
+    needs: scan
+    steps:
+      - name: download artifact 
+        uses: actions/download-artifact@v4
+        with: 
+          name: images
+          path: .
+      - name: check if image is available in runner 
+        run: docker images
+      - name: load image to local daemon 
+        run: docker load -i images.tar 
+      - name: login to amazon 
+        uses: aws-actions/configure-aws-credentials@v5 
+        with: 
+          role-to-assume: ${{env.AWS_ROLE}}
+          aws-region: eu-north-1
       - name: login to ecr 
-        id: login-ecr
-        uses: aws-actions/amazon-ecr-login@v2
-      - name: push to aws 
+        id: login-ecr 
+        uses: aws-actions/amazon-ecr-login@v2 
+      - name: push images 
         run: | 
-          docker tag ${{env.REG}}${{env.REPO}}:latest ${{env.REG}}${{env.REPO}}:${{env.IMAGE_TAG}}
-          docker push ${{env.REG}}${{env.REPO}}:latest
-          docker push ${{env.REG}}${{env.REPO}}:${{env.IMAGE_TAG}}
-      - name: send notification to email
+          docker tag ${{needs.scan.outputs.image-tag}} ${{env.ECR_REG}}${{env.ECR_REPO}}:latest
+          docker push ${{env.ECR_REG}}${{env.ECR_REPO}}:latest
+          docker push ${{needs.scan.outputs.image-tag}}
+    
+      - name: send a email notification to team 
         run: |
           aws sns publish \
-          --topic-arn ${{env.Email}} \
+          --topic-arn ${{env.EMAIL}} \
           --subject "workflow successful" \
-          --message "The pipeline ran successfully and the image with ID: ${{env.REG}}${{env.REPO}}"
+          --message "The workflow ran successfully and created an image with ID: ${{env.ECR_REG}}${{env.ECR_REPO}}:latest" \
